version: "3"

services:
  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    # Indica de forma fixa a plataforma na qual o banco irá rodar
    platform: linux/x86_64
    restart: always
    ports:
      # Garanta que não haverá conflitos de porta com um banco que esteja
      # rodando localmente
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
